version: 2
updates:
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: weekly
    time: '04:00'
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/server"
  schedule:
    interval: weekly
    time: '04:00'
  open-pull-requests-limit: 10